### ISSUE TITLE
[FR] Better search

### ISSUE THREAD

**Issue by NightMachinary** [dash-docs-el/dash-docs#12]
It would be very convenient if dash-docs supported stronger search engines, such as `ugrep --bool` (a kind of regex with space acting as `AND`), or `fzf --filter`. The current search requires typing things very precisely.

**Comment by canatella** [comment]
From what I understand, dash docsets are a sqlite database that's queried which makes it super fast, but then you can't just use any tool to grep the doc...

**Comment by kidd** [comment]
that is correct, sqlite is used to do the searches. still, we do some `like "%whatever%you%typed"` inlining to make it fuzzyish, but that's about it.

Maybe using ft5 could help, but I doubt it would make much of a difference, because the contents of the docs are in the html anyway, which is not indexed at all.
